pluginManagement {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        gradlePluginPortal()
        jcenter()
        /* maven {
             url 'https://raw.github.com/iainconnor/ObjectCache/master/maven/'
         }*/
        maven { url "https://jitpack.io" }
        maven {
            url 'https://raw.github.com/iainconnor/ObjectCache/master/maven/'
        }

        maven { url 'https://artifact.bytedance.com/repository/Volcengine/' }
        maven {
            url "https://artifact.bytedance.com/repository/thrall_ck/"
            credentials {
                username = MAVEN_USER_NAME
                password = MAVEN_PASS_WORD
            }
            authentication {
                digest(BasicAuthentication)
            }
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        jcenter()
        /* maven {
             url 'https://raw.github.com/iainconnor/ObjectCache/master/maven/'
         }*/
        maven { url "https://jitpack.io" }
        maven {
            url 'https://raw.github.com/iainconnor/ObjectCache/master/maven/'
        }
        maven { url 'https://artifact.bytedance.com/repository/Volcengine/' }
        maven {
            url "https://artifact.bytedance.com/repository/thrall_ck/"
            credentials {
                username = MAVEN_USER_NAME
                password = MAVEN_PASS_WORD
            }
            authentication {
                digest(BasicAuthentication)
            }
        }
    }
}
rootProject.name = "shortvideo"
include ':app'
include ':export'
